#Trainer
epochs: 2000
validation_len: 32

#Callbacks
early_stop_patience: 16
monitor: "val_loss"
mode: "min"
reduce_lr_patience: 8
reduce_lr_factor: 0.5
min_lr: 0.0001


#Compiler
learning_rate: 0.001
clipnorm: 1
delta: 0.8